name: checked_mirrors
version: 0.1.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  A wrapper on top of dart:mirrors that can check whether @MirrorsUsed is
  missing in your application.
homepage: https://www.dartlang.org/
dependencies:
  logging: ">=0.9.1 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.2+1 <0.10.0"
environment:
  sdk: ">=1.1.0-dev.5.0 <2.0.0"
